{:db-spec {:db "tcp://localhost:9092/nio:~/projects/jsk/resources/db/jsk.db;AUTO_SERVER=TRUE"
           :subname "tcp://localhost:9092/nio:~/projects/jsk/resources/db/jsk.db;AUTO_SERVER=TRUE"
           :classname "org.h2.Driver"
           :user "sa"
           :subprotocol "h2"
           :password ""}

 :email-conf {:host "smtp.gmail.com"
              :port 587
              :user "user@gmail.com"
              :pass "user-pass"}

:error-email-to "xfthhxk@gmail.com"

 ; These are the logs generated by the jobs being run
 ; Each execution has its own log file.
 ; Stdout and stderr are slurped and get saved here.
 :execution-log-directory "/tmp/jsk-execution-log"}
