{:db-spec
 ;; {:db "tcp://localhost:9092/nio:~/projects/jsk/resources/db/jsk.db;AUTO_SERVER=TRUE"
 ;;  :subname "tcp://localhost:9092/nio:~/projects/jsk/resources/db/jsk.db;AUTO_SERVER=TRUE"
 ;;  :classname "org.h2.Driver"
 ;;  :user "sa"
 ;;  :subprotocol "h2"
 ;;  :password ""}

 {:db "test"
  :subname "//localhost:3306/test?zeroDateTimeBehavior=convertToNull"
  :classname "com.mysql.jdbc.Driver"
  :user "root"
  :subprotocol "mysql"
  :password ""}

 :email-conf {:host "smtp.domain.com"
              :port 587
              :user "user@domain.com"
              :pass "your-password-here"}

:error-email-to "user@domain.com"

 ; These are the logs generated by the jobs being run
 ; Each execution has its own log file.
 ; Stdout and stderr are slurped and get saved here.
 :execution-log-directory "/tmp/jsk-execution-log"

 ; heartbeat interval
 ; agents are considered dead after not receiving heartbeats after :dead-after-milliseconds
 :heartbeats {:interval-milliseconds 1000
              :dead-after-milliseconds 30000}
 }
